### PR TITLE
Update to 1.6.0 with dependency updates

### PR DESCRIPTION
**Pull request by snowman2**
Checklist
* [x]  Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by snowman2** [comment]
@conda-forge-admin please re-render.

**Comment by snowman2** [comment]
@conda-forge-admin, please re-render.

**Comment by snowman2** [comment]
@conda-forge/datacube it is cleared for launch!

**Comment by omad** [comment]
Thanks

**Pull request merged**
